---
- hosts: web
  become: yes
  tasks:
    - name: Update packages (best effort)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      ignore_errors: yes

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Create test page
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Ansible — It works!</h1>
          <p>Managed by Ansible on {{ inventory_hostname }}</p>

    - name: Enable & start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
